/***************************************************************************
 *
 * R2RML Model : TriplesMap Interface
 *
 * (C) 2011 Antidot (http://www.antidot.net)
 *
 * Module			:	R2RMLModel
 * 
 * Fichier			:	TriplesMap.java
 *
 * Description		:	A triples map specifies a rule for translating each
 * 						row of a logical table to zero or more RDF triples.
 * 
 * Reference		:	R2RML: RDB to RDF Mapping Language
 * 						W3C Working Draft 20 September 2011
 *
 * Options de compilation:
 *
 * Auteurs(s)			:	JHO
 *
 *
 ****************************************************************************/
package net.antidot.semantic.rdf.rdb2rdf.r2rml.model;

import java.util.Set;

import net.antidot.semantic.rdf.rdb2rdf.r2rml.exception.InvalidR2RMLStructureException;

public interface TriplesMap {

	/**
	 * It must have exactly one logical table, which specifies a
	 * SQL query result to be mapped to triples.
	 */
	public LogicalTable getLogicalTable();
	public void setLogicalTable(LogicalTable logicalTable);
	
	/**
	 * It must have exactly one subject map that specifies how to generate
	 * the subjects for each row of the logical table.
	 */
	public SubjectMap getSubjectMap();
	public void setSubjectMap(SubjectMap stdSubjectMap) throws InvalidR2RMLStructureException;

	/**
	 * It may have zero or more rr:predicateObjectMap properties, whose values 
	 * must be predicate-object maps. Each specifies a predicate-object pair 
	 * that, together with the subjects generated by the subject map,
	 * may form one RDF triple for each row.
	 * 
	 * @return
	 */
	public Set<PredicateObjectMap> getPredicateObjectMaps();
	public void addPredicateObjectMap(PredicateObjectMap predicateObjectMap);
	
	
	

	

}
